### ISSUE TITLE
Income Financial Verification Popup

### ISSUE THREAD

**Issue by penoptech** [Get-Your/GetFoco#128]
Tim, The pop up menu on Step 5 of 6 (Income Verification) is: 

Please upload you EBT card form your EBT account, take a screen shot just like the image below. For physical cards, please make sure the name and card are clear for IDs. Please take both a front and back picture like the below. 

It creates a lot of confusion for folks not using EBT cards. And, we don't’ need the back of anything. Can we change asap to:

Please upload a card, a copy of an email, or a letter from qualifying programs. Take a screen shot like the example of the EBT card. Please make sure the names and information are clear.

**Comment by TiCampbell** [comment]
Sounds great, please take this on while I clean up the `dev` branch. I did put some comments in #68 that I copied below (and I'll remove them from that task, since it's about the future state, including the 'upload successful!' message).

- Remove the back of the EBT card image (we don't need the back of any card)
- Change the wording to: "Please upload a card, a copy of an email, or a letter from qualifying programs. Take a screen shot like the example of the EBT card. Please make sure the names and information are clear."
